;; -*- mode: eask; lexical-binding: t -*-

(package "mcp"
         "0.1.0"
         "Model Context Protocol")

(website-url "https://github.com/lizqwerscott/mcp.el")
(keywords "tools")

(package-file "mcp.el")
(files "mcp.el"
       "mcp-hub.el")

(source 'gnu)
(source 'nongnu)
(source 'melpa)

(depends-on "emacs" "30.1")
(depends-on "jsonrpc" "1.0.25")

(development
 (depends-on "elisp-lint")
 (depends-on "package-lint")
 (depends-on "undercover"))
